# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import KDIPgRPC_pb2 as KDIPgRPC__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class KDIP_NetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientSignalService = channel.unary_unary(
                '/KDIPgRPC_proto.KDIP_NetService/ClientSignalService',
                request_serializer=KDIPgRPC__pb2.Message.SerializeToString,
                response_deserializer=KDIPgRPC__pb2.Message.FromString,
                )
        self.VisionDataService = channel.unary_unary(
                '/KDIPgRPC_proto.KDIP_NetService/VisionDataService',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=KDIPgRPC__pb2.ImageDataPacket.FromString,
                )


class KDIP_NetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientSignalService(self, request, context):
        """★ (Unary) Client Signal Channel
        Server <-- Client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VisionDataService(self, request, context):
        """★ (Server Streaming) Monitoring Channel
        Server  --> Client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KDIP_NetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientSignalService': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientSignalService,
                    request_deserializer=KDIPgRPC__pb2.Message.FromString,
                    response_serializer=KDIPgRPC__pb2.Message.SerializeToString,
            ),
            'VisionDataService': grpc.unary_unary_rpc_method_handler(
                    servicer.VisionDataService,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=KDIPgRPC__pb2.ImageDataPacket.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KDIPgRPC_proto.KDIP_NetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KDIP_NetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientSignalService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KDIPgRPC_proto.KDIP_NetService/ClientSignalService',
            KDIPgRPC__pb2.Message.SerializeToString,
            KDIPgRPC__pb2.Message.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VisionDataService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KDIPgRPC_proto.KDIP_NetService/VisionDataService',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            KDIPgRPC__pb2.ImageDataPacket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
