# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KDIPgRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eKDIPgRPC.proto\x12\x0eKDIPgRPC_proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x07Message\x12\x0e\n\x06UserID\x18\x01 \x01(\t\x12\x13\n\x0bUserMessage\x18\x02 \x01(\t\"@\n\x0fImageDataPacket\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x10\n\x08LayerNum\x18\x02 \x01(\x05\x12\r\n\x05\x44\x61tas\x18\x03 \x01(\x0c\x32\xa8\x01\n\x0fKDIP_NetService\x12G\n\x13\x43lientSignalService\x12\x17.KDIPgRPC_proto.Message\x1a\x17.KDIPgRPC_proto.Message\x12L\n\x11VisionDataService\x12\x16.google.protobuf.Empty\x1a\x1f.KDIPgRPC_proto.ImageDataPacketb\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_IMAGEDATAPACKET = DESCRIPTOR.message_types_by_name['ImageDataPacket']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'KDIPgRPC_pb2'
  # @@protoc_insertion_point(class_scope:KDIPgRPC_proto.Message)
  })
_sym_db.RegisterMessage(Message)

ImageDataPacket = _reflection.GeneratedProtocolMessageType('ImageDataPacket', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATAPACKET,
  '__module__' : 'KDIPgRPC_pb2'
  # @@protoc_insertion_point(class_scope:KDIPgRPC_proto.ImageDataPacket)
  })
_sym_db.RegisterMessage(ImageDataPacket)

_KDIP_NETSERVICE = DESCRIPTOR.services_by_name['KDIP_NetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=63
  _MESSAGE._serialized_end=109
  _IMAGEDATAPACKET._serialized_start=111
  _IMAGEDATAPACKET._serialized_end=175
  _KDIP_NETSERVICE._serialized_start=178
  _KDIP_NETSERVICE._serialized_end=346
# @@protoc_insertion_point(module_scope)
